Pass current variable to environment setter explicitly
* mrblib/resource_executor/cron.rb (set_environment_var):
Handle "current" keyword variable by explicitly accepting the passed value to
prevent nil error "undefined method 'environment' (NoMethodError)".
* (load_current_resource): Provide current variable to the method.

Excerpt from Hocho log sample:

  [host] DEBUG :     cron[sample]
  [host] DEBUG :       cron[sample] action: create
  [host] DEBUG :         (in set_desired_attributes)
  [host] DEBUG :         (in set_current_attributes)
  [host] DEBUG :         Executing `crontab -l -u root`...
  [host] DEBUG :         stdout | # ...
  [host] DEBUG :         stdout |
  [host] DEBUG :           exited with 0
  [host] DEBUG :         Found cron 'sample'
  [host/ERR] trace (most recent call last):
  [host/ERR] 	[3] /path/to/Hocho/tmpdir/itamae/plugins/mitamae-plugin-resource-cron/mrblib/resource_executor/cron.rb:54:in set_current_attributes
  [host/ERR] 	[2] /path/to/Hocho/tmpdir/itamae/plugins/mitamae-plugin-resource-cron/mrblib/resource_executor/cron.rb:67:in load_current_resource
  [host/ERR] 	[1] /path/to/Hocho/tmpdir/itamae/plugins/mitamae-plugin-resource-cron/mrblib/resource_executor/cron.rb:75:in load_current_resource
  [host/ERR] /path/to/Hocho/tmpdir/itamae/plugins/mitamae-plugin-resource-cron/mrblib/resource_executor/cron.rb:207:in set_environment_var: undefined method 'environment' (NoMethodError)
  $ shred --remove /path/to/Hocho/tmpdir
  => host $ rm -rf /path/to/Hocho/tmpdir/itamae
  $ rm -rf /path/to/Hocho/tmpdir/itamae
  /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/ssh_base.rb:240:in `ssh_run': execution failed on host (status=1, signal=nil): "bash" (RuntimeError)
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/mitamae.rb:76:in `block (2 levels) in run_mitamae'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/ssh_base.rb:105:in `prepare_sudo'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/mitamae.rb:74:in `block in run_mitamae'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/ssh_base.rb:220:in `with_host_node_json_file'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/mitamae.rb:68:in `run_mitamae'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/mitamae.rb:20:in `block in run'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/ssh_base.rb:46:in `deploy'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/drivers/mitamae.rb:18:in `run'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/runner.rb:22:in `run'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/command.rb:85:in `block in apply'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/command.rb:77:in `each'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/lib/hocho/command.rb:77:in `apply'
      from /path/to/Thor/source/lib/ruby/vendor_ruby/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
      from /path/to/Thor/source/lib/ruby/vendor_ruby/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
      from /path/to/Thor/source/lib/ruby/vendor_ruby/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
      from /path/to/Thor/source/lib/ruby/vendor_ruby/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
      from /path/to/Hocho/source/lib/ruby/vendor_ruby/gems/hocho-0.3.8/bin/hocho:4:in `<top (required)>'
      from /path/to/Hocho/source/bin/.real/hocho:25:in `load'
      from /path/to/Hocho/source/bin/.real/hocho:25:in `<top (required)>'
      from /path/to/profile/bin/hocho:4:in `load'
      from /path/to/profile/bin/hocho:4:in `<main>'